name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  documentation:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Enable dev tooling
        run: touch .dev-tooling

      - name: Build Documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target SwiduxMixpanelAnalytics \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path /SwiduxMixpanelAnalytics \
            --output-path ./docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          branch: gh-pages
          folder: docs
